### ISSUE TITLE
Doesn't work with cross account roles.

### ISSUE THREAD

**Issue by varunchandak** [matheussilvasantos/dynamocli#2]

**Comment by matheussilvasantos** [comment]
I've followed the section Switch Roles (AWS CLI) on [Tutorial: Delegate Access Across AWS Accounts Using IAM Roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html) and I was able to use the commands of `dynamocli`. What error are you getting?

**Comment by matheussilvasantos** [comment]
I think you have two profiles on your `~/.aws/credentials` file, as you explain in your article [Using AWS CLI with Cross Account Access ](https://vrnchndk.in/2017/04/02/Using-AWS-CLI-with-Cross-Account-Access/). In this case, you can run `dynamocli` passing the `AWS_PROFILE` environment variable with the profile you want to use, for example: `AWS_PROFILE=testaccount dynamocli erase users`.

**Comment by varunchandak** [comment]
okay, the AWS says to use `AWS_DEFAULT_PROFILE` use a specific profile. I'll give a try using `AWS_PROFILE`. Thanks

**Comment by matheussilvasantos** [comment]
Okay, keep me updated :smile:.
